/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mn_uwvm_Parson */

#ifndef _Included_mn_uwvm_Parson
#define _Included_mn_uwvm_Parson
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     mn_uwvm_Parson
 * Method:    jsonParseString
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_mn_uwvm_Parson_jsonParseString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     mn_uwvm_Parson
 * Method:    jsonObjectGetValue
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_mn_uwvm_Parson_jsonObjectGetValue
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     mn_uwvm_Parson
 * Method:    jsonObjectGetString
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_mn_uwvm_Parson_jsonObjectGetString
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     mn_uwvm_Parson
 * Method:    jsonObjectGetObject
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_mn_uwvm_Parson_jsonObjectGetObject
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     mn_uwvm_Parson
 * Method:    jsonObjectGetArray
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_mn_uwvm_Parson_jsonObjectGetArray
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     mn_uwvm_Parson
 * Method:    jsonObjectGetNumber
 * Signature: (JLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_mn_uwvm_Parson_jsonObjectGetNumber
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     mn_uwvm_Parson
 * Method:    jsonObjectGetBoolean
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_mn_uwvm_Parson_jsonObjectGetBoolean
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     mn_uwvm_Parson
 * Method:    jsonObjectDotgetValue
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_mn_uwvm_Parson_jsonObjectDotgetValue
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     mn_uwvm_Parson
 * Method:    jsonObjectDotgetString
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_mn_uwvm_Parson_jsonObjectDotgetString
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     mn_uwvm_Parson
 * Method:    jsonObjectDotgetObject
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_mn_uwvm_Parson_jsonObjectDotgetObject
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     mn_uwvm_Parson
 * Method:    jsonObjectDotgetArray
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_mn_uwvm_Parson_jsonObjectDotgetArray
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     mn_uwvm_Parson
 * Method:    jsonObjectDotgetNumber
 * Signature: (JLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_mn_uwvm_Parson_jsonObjectDotgetNumber
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     mn_uwvm_Parson
 * Method:    jsonObjectDotgetBoolean
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_mn_uwvm_Parson_jsonObjectDotgetBoolean
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     mn_uwvm_Parson
 * Method:    jsonObjectGetCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_mn_uwvm_Parson_jsonObjectGetCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     mn_uwvm_Parson
 * Method:    jsonObjectGetName
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_mn_uwvm_Parson_jsonObjectGetName
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     mn_uwvm_Parson
 * Method:    jsonArrayGetValue
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_mn_uwvm_Parson_jsonArrayGetValue
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     mn_uwvm_Parson
 * Method:    jsonArrayGetString
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_mn_uwvm_Parson_jsonArrayGetString
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     mn_uwvm_Parson
 * Method:    jsonArrayGetObject
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_mn_uwvm_Parson_jsonArrayGetObject
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     mn_uwvm_Parson
 * Method:    jsonArrayGetArray
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_mn_uwvm_Parson_jsonArrayGetArray
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     mn_uwvm_Parson
 * Method:    jsonArrayGetNumber
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_mn_uwvm_Parson_jsonArrayGetNumber
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     mn_uwvm_Parson
 * Method:    jsonArrayGetBoolean
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_mn_uwvm_Parson_jsonArrayGetBoolean
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     mn_uwvm_Parson
 * Method:    jsonArrayGetCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_mn_uwvm_Parson_jsonArrayGetCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     mn_uwvm_Parson
 * Method:    jsonValueGetType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_mn_uwvm_Parson_jsonValueGetType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     mn_uwvm_Parson
 * Method:    jsonValueGetObject
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_mn_uwvm_Parson_jsonValueGetObject
  (JNIEnv *, jclass, jlong);

/*
 * Class:     mn_uwvm_Parson
 * Method:    jsonValueGetArray
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_mn_uwvm_Parson_jsonValueGetArray
  (JNIEnv *, jclass, jlong);

/*
 * Class:     mn_uwvm_Parson
 * Method:    jsonValueGetString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_mn_uwvm_Parson_jsonValueGetString
  (JNIEnv *, jclass, jlong);

/*
 * Class:     mn_uwvm_Parson
 * Method:    jsonValueGetNumber
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_mn_uwvm_Parson_jsonValueGetNumber
  (JNIEnv *, jclass, jlong);

/*
 * Class:     mn_uwvm_Parson
 * Method:    jsonValueGetBoolean
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_mn_uwvm_Parson_jsonValueGetBoolean
  (JNIEnv *, jclass, jlong);

/*
 * Class:     mn_uwvm_Parson
 * Method:    jsonValueFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_mn_uwvm_Parson_jsonValueFree
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
